name: Build and Release

on:
  push:
    tags:
      - v*

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Action / Checkout
        uses: actions/checkout@v3.1.0

      - name: Action / Setup Node v16
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16

      - name: Yarn / Install Dependencies
        run: |
          yarn install

      - name: Yarn / Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn run build

      - name: Action / Release
        uses: ncipollo/release-action@v1.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          generateReleaseNotes: true
          artifacts: build/release/steam-acf-generator.zip
