name: Build and Release

on:
  push:
    tags:
      - v*

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Action / Checkout
        uses: actions/checkout@v3.0.2

      - name: Action / Setup Node v16
        uses: actions/setup-node@v3.3.0
        with:
          node-version: '16'

      - name: Yarn / Install Dependencies
        run: |
          yarn install

      - name: Yarn / Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn run release

      - name: Action / Release
        uses: ncipollo/release-action@v1.10.0
        with:
          token: ${{ secrets.YOUR_GITHUB_TOKEN }}
          draft: true
          generateReleaseNotes: true
          artifacts: 'build/release/steam-acf-generator.zip'
